# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VerilogCode/washing_machine/washing_machine.cache/wt [current_project]
set_property parent.project_path D:/VerilogCode/washing_machine/washing_machine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/show_seg.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/num2seg.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/disp_num.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/divider.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/format_disp.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/countdown.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/main.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/test.v
  D:/VerilogCode/washing_machine/washing_machine.srcs/sources_1/new/sel_mode.v
}
read_xdc D:/VerilogCode/washing_machine/washing_machine.srcs/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/VerilogCode/washing_machine/washing_machine.srcs/Nexys4DDR_Master.xdc]

synth_design -top main -part xc7a100tcsg324-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
